version: "3.8"
services:
  # app:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #     - redis
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: notes_app
      MYSQL_ROOT_PASSWORD: password # for username root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "redis_password"]
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis_password
volumes:
  db_data: {}
